/* Germany environmental controversies / original local v6 viewer. Data loaded separately. */
const ALL=window.GermanEnvironment06Data;

const $=id=>document.getElementById(id),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette={policy:'#e5ba76',organization:'#73d2c0',facility_story:'#bad2fb',facility:'#b5b5f8',archive:'#cc8e82'};
const facilityColors={retired:'#b5b5f8',awarded:'#eaa36b',ordered:'#e9d086',scheduled:'#7dbbd9'};const colorOf=e=>e.kind==='facility'?facilityColors[e.facility_phase]||palette.facility:e.kind==='archive'?actionDefs[e.action_group].color:palette[e.kind];
const titles={overview:'争议政策及核电／煤电机组退出',focus:'争议重点案例',policy:'环保政策：出台地或实施地点',organization:'环保组织：具体项目争议',facility:'能源设施：历史退役／退出安排／未来期限',archive:'行动事件：交通、能源、设施、文化、工程'};
const hints={overview:'政策及实际退役电厂，另附法定未来煤电退出安排（蓝色标记），计划日期不是已停机事实。其他中标和监管设施请切换至能源设施。',focus:'精选政策与组织项目，不代表全德国全部环保行动。点位仅是对应设施、政策发布地或事件位置。',policy:'联邦法律放在表决或发布地点，具体影响需结合下方相关电站查看。',organization:'选择组织可同时发现它在其他地区的行动记录；法律异议不直接等同于违法阻工。',facility:'按状态分别查看17台核电、15条历史煤电记录、36项尚需核实实际停机的中标设施、3项监管命令及21项法定未来退出安排。',archive:'机场封锁、喷漆、能源阻断等记录全部保留，按实际行为分为五类；点击地图点位可查看司法后续和经济证据。'};
const actionDefs={traffic:{name:'交通干扰',color:'#ee9b63',path:'M11 1C10 1 9 2 9 3V9L3 13V16L9 14V20L6 22V23L12 21L18 23V22L15 20V14L21 16V13L15 9V3C15 2 14 1 13 1Z'},energy:{name:'能源干扰',color:'#f2be65',path:'M13 2 3 14h7l-1 8L21 9h-8V2Z'},sabotage:{name:'设施破坏',color:'#f17875',path:'M12 22c4.5 0 7-3.5 7-7 0-4-3-5-3.3-9-2 2-2 4-3 5-1-4-2.2-6-3.5-8C8.5 8 5 10.5 5 15c0 4 2.5 7 7 7Z'},culture:{name:'文化破坏',color:'#c9cdd0',path:'M3 10h18M5 10v9M10 10v9M15 10v9M20 10v9M2 21h20M12 2 2 7v3h20V7Z'},construction:{name:'工程冲击',color:'#9ab9c5',path:'M2 19h20M5 19V4h4v15M15 19V8h4v11M5 7l14 11M2 10l4-3M18 7l4 3'}};
const iconSvg=(a)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${actionDefs[a].path}" ${a==='traffic'?'style="fill:currentColor"':''}/></svg>`;
const state={mode:'overview',action:'all',facilityPhase:'all',org:'all',search:'',selected:null,zoom:1,tx:0,ty:0};
for(const b of document.querySelectorAll('[data-phase]'))b.onclick=()=>{state.facilityPhase=b.dataset.phase;document.querySelectorAll('[data-phase]').forEach(x=>x.classList.toggle('active',x===b));render()};
for(const b of document.querySelectorAll('[data-action]')){const t=b.dataset.action;if(t!=='all'){b.style.color=actionDefs[t].color;b.innerHTML=iconSvg(t)+`<span>${actionDefs[t].name}</span><em id="ac-${t}"></em>`}b.onclick=()=>{state.action=t;document.querySelectorAll('[data-action]').forEach(x=>x.classList.toggle('active',x===b));render()}}
function membership(e){return state.mode==='overview'?(['policy','facility_story'].includes(e.kind)||(e.kind==='facility'&&['retired','scheduled'].includes(e.facility_phase))):state.mode==='focus'?['policy','organization','facility_story'].includes(e.kind):state.mode==='policy'?e.kind==='policy':state.mode==='organization'?e.kind==='organization':state.mode==='facility'?e.kind==='facility':e.kind==='archive'}
function visible(){let arr=ALL.filter(membership);if(state.org!=='all'){arr=ALL.filter(e=>(e.actor||'').toLowerCase().includes(state.org.toLowerCase())&&['organization','archive'].includes(e.kind))}if(state.mode==='archive'&&state.action!=='all'&&state.org==='all'){arr=arr.filter(e=>e.action_group===state.action)}if(state.mode==='facility'&&state.facilityPhase!=='all'&&state.org==='all'){arr=arr.filter(e=>e.facility_phase===state.facilityPhase)}if(state.search){arr=arr.filter(e=>[e.title,e.actor,e.city,e.summary,e.dispute,e.outcome].some(v=>String(v||'').toLocaleLowerCase().includes(state.search)))}return arr.sort((a,b)=>(a.facility_phase==='scheduled'?1:0)-(b.facility_phase==='scheduled'?1:0)||b.date.localeCompare(a.date)||a.title.localeCompare(b.title))}
const rad=lat=>Math.log(Math.tan(Math.PI/4+lat*Math.PI/360));function point(e){let {lat,lon}=e.coordinates;return{x:(lon-3.4)/14.5*920,y:(rad(56.5)-rad(lat))/(rad(56.5)-rad(46.4))*900}};
function pan(){ $('geoLayer').setAttribute('transform',`translate(${state.tx} ${state.ty}) scale(${state.zoom})`)}
function choose(id,center){const e=ALL.find(x=>x.id===id);if(!e)return;state.selected=id;details(e);document.querySelectorAll('.entry,.mark').forEach(a=>a.classList.toggle('selected',a.dataset.id===id));if(center){let p=point(e);state.zoom=Math.max(1.35,state.zoom);state.tx=460-p.x*state.zoom;state.ty=450-p.y*state.zoom;pan()}}
function groupFrom(e){let str=e.actor.toLowerCase();return str.includes('bund')?'BUND':str.includes('nabu')?'NABU':str.includes('duh')?'DUH':str.includes('greenpeace')?'Greenpeace':str.includes('ende gelände')?'Ende Gelände':str.includes('letzte generation')?'Letzte Generation':str.includes('tesla stoppen')?'Tesla Stoppen':null}
function details(e){if(!e){$('detail').innerHTML='<div class="secname">MAP GUIDE</div><h2>点击地图上的行动或政策点位，查看究竟发生了什么</h2><p class="subtitle2">先看谁提出政策或采取行动，再看它影响了什么、结果如何，以及事实与推断之间的差别。</p><div class="notice">本专题挑选有实际争议的政策与事件，不为环保组织臆测隐秘动机。正常生态修复项目不在这张争议地图的收录范围内。</div>';return}
const typ=e.kind==='policy'?'政策决策':e.kind==='organization'?'组织参与':e.kind==='facility_story'?'设施争议':e.kind==='facility'?'能源设施':actionDefs[e.action_group]?.name||'行动事件', section=(label,value)=>value?`<section class="detailsection"><h3>${label}</h3><p>${safe(value)}</p></section>`:'';
const src=(e.sources||[]).map(v=>`<a href="${safe(v.url)}" target="_blank" rel="noopener noreferrer">↗ ${safe(v.publisher)}</a>`).join('');let actor=groupFrom(e);
$('detail').innerHTML=`<div class="secname">${typ.toUpperCase()} / ${safe(e.city)}</div><h2>${safe(e.title)}</h2><div class="chiprow"><span class="chip" style="border-color:${colorOf(e)};color:${colorOf(e)}">${typ}</span><span class="chip">${safe(e.date)}</span>${e.status_label?`<span class="chip" style="color:${facilityColors[e.facility_phase]||'#dbd8e6'}">${safe(e.status_label)}</span>`:''}<span class="chip">${safe(e.actor)}</span></div>${section('做了什么',e.summary)}${e.auction_awards?section('官方招标中标记录',e.auction_awards.map(a=>a.award_id+' · '+a.name+' · '+a.capacity_mw+' MW · 目标年'+a.legal_coal_ban_target_year).join('；')):''}${section('争议点',e.dispute)}${section('实际结果',e.outcome||e.measured_impact)}${section('司法／政策进展',e.court_followup||e.legal_status)}${section('经济影响／证据边界',e.limits||e.economic_evidence)}${e.capacity_mw?section('装机容量',e.capacity_mw+' MW（历史装机，不是净经济损失）'):''}<div class="detailsection sources"><h3>原始资料</h3>${src}</div><div class="notice">位置类型：${e.location_type==='legislature'?'立法或政策发布地点，并非全国政策仅影响此处':e.location_type==='facility'?'能源设施附近定位':e.location_type==='municipality'?'市镇级近似定位，并非电厂精确经纬度': '事件或项目的区域级定位'}；不推断未经证实的损失或动机。</div>${actor?`<button class="smallbtn" data-actor="${safe(actor)}">只看 ${safe(actor)} 的地点 ↗</button>`:''}`;let b=$('detail').querySelector('[data-actor]');if(b)b.onclick=()=>{state.org=b.dataset.actor;$('org').value=state.org;render()};}
function render(){const list=visible(),root=$('entries'),pts=$('points');root.replaceChildren();pts.replaceChildren();$('count').textContent=list.length;$('kindCount').textContent=new Set(list.map(e=>e.city)).size;$('listTitle').textContent=state.org!=='all'?`${state.org} · 关联地图`:titles[state.mode];$('listHint').textContent=state.org!=='all'?'仅显示与所选组织明确相关的事件。':hints[state.mode];$('actionbar').hidden=state.mode!=='archive'||state.org!=='all';$('facilitybar').hidden=state.mode!=='facility'||state.org!=='all';for(const phase of ['all','retired','awarded','ordered','scheduled']){const count=phase==='all'?ALL.filter(e=>e.kind==='facility').length:ALL.filter(e=>e.kind==='facility'&&e.facility_phase===phase).length;const el=$('fc-'+phase);if(el)el.textContent=count;}const counts={all:0,traffic:0,energy:0,sabotage:0,culture:0,construction:0};for(const e of ALL){if(e.kind==='archive'){counts.all++;counts[e.action_group]++}}for(const k of Object.keys(counts)){const el=$('ac-'+k);if(el)el.textContent=counts[k]}$('legend').innerHTML=state.mode==='archive'?Object.entries(actionDefs).map(([k,v])=>`<span><i class="swatch" style="background:${v.color}"></i>${v.name}</span>`).join(''):'<span><i class="swatch" style="background:#e5ba76"></i>政策</span><span><i class="swatch" style="background:#b5b5f8"></i>历史退役</span><span><i class="swatch" style="background:#eaa36b"></i>中标</span><span><i class="swatch" style="background:#e9d086"></i>监管命令</span><span><i class="swatch" style="background:#7dbbd9"></i>未来计划</span>';if(!list.length){root.innerHTML='<div class="empty">暂时没有符合条件的地点。</div>'}const coloc={};list.forEach(e=>{let p=point(e);let key=Math.round(p.x/8)+'-'+Math.round(p.y/8);(coloc[key]??=[]).push(e.id)});list.forEach(e=>{const c=colorOf(e),row=document.createElement('button');row.className='entry'+(state.selected===e.id?' selected':'');row.dataset.id=e.id;row.innerHTML=(e.kind==='archive'?`<span class="iconbox" style="color:${c}">${iconSvg(e.action_group)}</span>`:`<span class="dotico ${safe(e.kind)}" style="background:${c}"></span>`)+`<span><div class="entryname">${safe(e.title)}</div><div class="entrysub">${safe(e.city)} · ${e.date}${e.status_label?' · '+safe(e.status_label):''}</div></span>`;row.onclick=()=>choose(e.id,true);root.append(row);
let p=point(e),key=Math.round(p.x/8)+'-'+Math.round(p.y/8),grp=coloc[key],slot=grp.indexOf(e.id);if(grp.length>1){const a=slot*2*Math.PI/grp.length;const r=11+Math.min(28,grp.length*2.2);p.x+=Math.cos(a)*r;p.y+=Math.sin(a)*r}const svgNS='http://www.w3.org/2000/svg';let el;if(e.kind==='archive'){el=document.createElementNS(svgNS,'g');el.classList.add('action-mark');el.setAttribute('transform',`translate(${p.x} ${p.y})`);let bg=document.createElementNS(svgNS,'circle');bg.setAttribute('r',12);bg.setAttribute('stroke',c);bg.classList.add('markbg');el.append(bg);let path=document.createElementNS(svgNS,'path');path.setAttribute('d',actionDefs[e.action_group].path);path.setAttribute('stroke',c);path.setAttribute('fill',e.action_group==='traffic'?c:'none');path.setAttribute('transform','translate(-7.5 -7.5) scale(.625)');path.classList.add('markglyph');el.append(path)}else if(e.kind==='policy'){el=document.createElementNS(svgNS,'rect');el.setAttribute('x',p.x-7);el.setAttribute('y',p.y-7);el.setAttribute('width',14);el.setAttribute('height',14);el.setAttribute('rx',1);el.setAttribute('transform',`rotate(45 ${p.x} ${p.y})`)}else if(e.kind==='facility'){el=document.createElementNS(svgNS,'rect');el.setAttribute('x',p.x-5.2);el.setAttribute('y',p.y-5.2);el.setAttribute('width',10.4);el.setAttribute('height',10.4);el.setAttribute('rx',2)}else{el=document.createElementNS(svgNS,'circle');el.setAttribute('cx',p.x);el.setAttribute('cy',p.y);el.setAttribute('r',e.kind==='archive'?5.7:8)}el.setAttribute('fill',c);el.classList.add('mark');if(state.selected===e.id)el.classList.add('selected');el.dataset.id=e.id;el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',e.title);const name=document.createElementNS(svgNS,'title');name.textContent=e.date+' '+e.title;el.append(name);el.addEventListener('click',ev=>{ev.stopPropagation();choose(e.id,false)});el.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose(e.id,false)}});pts.append(el)});if(!list.find(e=>e.id===state.selected)){state.selected=null;details(null)}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.action='all';state.facilityPhase='all';document.querySelectorAll('[data-phase]').forEach(x=>x.classList.toggle('active',x.dataset.phase==='all'));document.querySelectorAll('[data-action]').forEach(x=>x.classList.toggle('active',x.dataset.action==='all'));state.org='all';$('org').value='all';document.querySelectorAll('[data-mode]').forEach(t=>t.classList.toggle('active',t===b));render()});$('search').oninput=e=>{state.search=e.target.value.toLocaleLowerCase().trim();render()};$('org').onchange=e=>{state.org=e.target.value;render()};function zoom(f){const nz=Math.min(4.5,Math.max(1,state.zoom*f));state.tx=460-(460-state.tx)*nz/state.zoom;state.ty=450-(450-state.ty)*nz/state.zoom;state.zoom=nz;if(nz===1){state.tx=0;state.ty=0}pan()};$('zin').onclick=()=>zoom(1.3);$('zout').onclick=()=>zoom(1/1.3);$('reset').onclick=()=>{state.zoom=1;state.tx=0;state.ty=0;pan()};$('mapSvg').addEventListener('wheel',ev=>{ev.preventDefault();zoom(ev.deltaY>0?.88:1.13)},{passive:false});let moving=false,last=null;const map=$('mapSvg');map.addEventListener('pointerdown',ev=>{if(ev.target.classList.contains('mark'))return;moving=true;last=[ev.clientX,ev.clientY];map.setPointerCapture(ev.pointerId);map.classList.add('dragging')});map.addEventListener('pointermove',ev=>{if(!moving)return;let b=map.getBoundingClientRect();state.tx+=(ev.clientX-last[0])*920/b.width;state.ty+=(ev.clientY-last[1])*900/b.height;last=[ev.clientX,ev.clientY];pan()});for(let type of ['pointerup','pointercancel'])map.addEventListener(type,()=>{moving=false;last=null;map.classList.remove('dragging')});render();
