#!/usr/bin/env python3
"""Rebuild Finance 08 historical debt and Rheinland-Pfalz regional cash-flow observations.

Read original, separately scoped official-source transcriptions in research/finance/a;
never blend stock and flow indicators or the county budget with the cities.
"""
import csv
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LOANS = ROOT / 'research/finance/a/state_municipal_loans_2021_2025.csv'
RP = ROOT / 'research/finance/a/rp_regional_finance_verified_2025_2026.csv'
OUT = Path(__file__).parent / 'finance-history.js'

with LOANS.open(encoding='utf-8-sig', newline='') as f:
    inputs = list(csv.DictReader(f))
state_index = defaultdict(lambda: {'cash': {}, 'investment': {}})
for record in inputs:
    year = int(record['year'])
    assert year in range(2021, 2026)
    if record['quality_flag'] == 'not_applicable_city_state':
        assert record['debt_million_eur'] == ''
        continue
    assert record['quality_flag'] == 'verified_report_table'
    assert record['debt_million_eur'].isdigit()
    state = record['state_iso']
    key = {'cash_loans': 'cash', 'investment_loans': 'investment'}[record['debt_type']]
    assert year not in state_index[state][key]
    state_index[state][key][year] = int(record['debt_million_eur'])

assert len(state_index) == 13
states = []
for state in sorted(state_index):
    obj = state_index[state]
    assert len(obj['cash']) == len(obj['investment']) == 5
    states.append({'id': state, 'cash': [obj['cash'][y] for y in range(2021, 2026)],
                   'investment': [obj['investment'][y] for y in range(2021, 2026)]})
total = {category: [sum(obj[category][index] for obj in states) for index in range(5)]
         for category in ('cash', 'investment')}
assert total['cash'] == [29461, 28109, 28960, 31789, 38587], total['cash']
assert total['investment'] == [100520, 109124, 122021, 134808, 155136], total['investment']

with RP.open(encoding='utf-8-sig', newline='') as f:
    rp_raw = list(csv.DictReader(f))
assert len(rp_raw) == 84
regional = []
for row in rp_raw:
    if row['period'] == '2025-full':
        # In core finance-data.js; do not duplicate a different nominal year/scope.
        continue
    assert row['period'] in ('2025-H1', '2026-H1')
    assert row['entity_scope'] in ('kreisfreie_stadt', 'landkreis_budget_only')
    assert len(row['ags5']) == 5
    balance = int(row['financing_balance_eur'])
    op = int(row['operating_balance_eur'])
    cap = int(row['capital_balance_eur'])
    assert abs(balance - op - cap) <= 250, (row['ags5'], row['period'])
    regional.append({
        'id': row['ags5'], 'name': row['name_de'], 'period': row['period'],
        'scope': 'city' if row['entity_scope'] == 'kreisfreie_stadt' else 'county_budget_only',
        'value': int(row['financing_balance_per_resident_eur']),
        'balance_eur': balance, 'operating_eur': op, 'capital_eur': cap,
        'source': row['source_url']
    })
assert len(regional) == 72
for period in ('2025-H1', '2026-H1'):
    rr = [r for r in regional if r['period'] == period]
    assert len(rr) == 36 and len([r for r in rr if r['scope'] == 'city']) == 12
    assert len([r for r in rr if r['scope'] == 'county_budget_only']) == 24
assert all(r['value'] < 0 for r in regional if r['period'] == '2026-H1' and r['scope'] == 'city')

payload = {
    'meta': {
        'years': [2021, 2022, 2023, 2024, 2025],
        'debt_unit': 'million_eur',
        'debt_scope': 'municipal_loans_13_non_city_states_excludes_integrated_affiliate_debt',
        'regional_unit': 'eur_per_person',
        'regional_scope': 'city_budget_or_county_budget_only_not_combined',
        'source_debt': 'https://www.bertelsmann-stiftung.de/fileadmin/files/Projekte/Monitor_Nachhaltige_Kommune/Finanzreport2026.pdf',
        'debt_pages': {'cash': 44, 'investment': 43},
        'as_of': '2026-10-10',
    },
    'totals': total,
    'states': states,
    'regional': regional,
}
OUT.write_text('/* Generated by build_finance_history.py; debt stock is NOT the balance flow. */\n'
               'window.GermanFinance08History=' + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'OK {len(states)} states x 5y x 2 debt types; {len(regional)} RP period rows, total cash 2025={total["cash"][-1]} mln EUR')